### PR TITLE
Add ic-repl to open repositories

### PR DESCRIPTION
**Pull request by chenyan-dfinity**
https://dfinity.atlassian.net/browse/IC-1474

### CODE REVIEW

**Comment by cgundy** [comment]
Hi @chenyan-dfinity - the github codeowners format is a little different from github. It requires that you first specify the files the team owns. If the team owns the entire repository, you need to reformat the codeowners file like this:

```
* @dfinity/dx
```

**Comment by chenyan-dfinity** [comment]
Fixed

**Comment by cgundy** [comment]
Hi, can you merge master in and rerun the workflow?

**Review by cgundy — APPROVED** [review]

**Comment by dfnitowner** [comment]
Dear @chenyan-dfinity,

In order to potentially merge your code in this open-source repository and therefore proceed with your contribution, we need to have your approval on DFINITY's [CLA](https://github.com/dfinity/cla/blob/main/CLA.md).

If you decide to agree with it, please visit this [issue](https://github.com/dfinity/cla/issues/231) and read the instructions there. Once you have signed it, re-trigger the workflow on this PR to see if your code can be merged.

— The DFINITY Foundation

**Comment by cgundy** [comment]
> The author is on dfinity organization member - CLA should not be required @cgundy

Yes and this repository does not accept external contributions. I need to fix the worfklow. Sorry about that!

@chenyan-dfinity you can disregard this comment and merge your PR!

**Pull request merged**
