### PR TITLE
Update open-repositories.txt to accept contributions to ic-observability-stack.

### PR DESCRIPTION
**Pull request by DFINITYManu**
In preparation for open sourcing it.

### CODE REVIEW

**Comment by cgundy** [comment]
@DFINITYManu has this been approved for opensourcing yet? If not I will close this and please reopen when it's ready, so that nobody from IDX accidentally merges it before it has received approval. Thank you!

**Comment by DFINITYManu** [comment]
This has been approved.

**Comment by DFINITYManu** [comment]
Approval link: https://dfinity.atlassian.net/browse/IC-1726

**Comment by DFINITYManu** [comment]
Why has this not yet been approved?

**Review by cgundy — APPROVED** [review]

**Pull request merged**
