### PR TITLE
feat: add internet-identity-playwright to open repos

### PR DESCRIPTION
**Pull request by peterpeterparker**
Open-sourcing ticket pending approvals: https://dfinity.atlassian.net/browse/IC-1779

### CODE REVIEW

**Comment by cgundy** [comment]
Check failed because no CODEOWNERS file is present. And we can't merge this until all approvals are given.

**Comment by cgundy** [comment]
Ah okay I think I see the issue - it's present but has no teams listed. The team that has write permissions in the repo also needs to be listed in the codeowners file.

**Comment by peterpeterparker** [comment]
Thanks @cgundy. I'm confused, I updated the repo similarly to what @frederikrothenberger did for other PR https://github.com/dfinity/repositories-open-to-contributions/pull/363 but here it fails 🤔

https://github.com/dfinity/internet-identity-playwright/blob/main/.github/CODEOWNERS

vs

https://github.com/dfinity/ic-canister-sig-creation/blob/main/.github/CODEOWNERS

**Comment by cgundy** [comment]
@peterpeterparker sorry for the confusion - the gix team needs to be listed as codeowners *and* have write permissions to the repo.

**Comment by peterpeterparker** [comment]
Frederik helped me, all good now. Thanks!

**Comment by cgundy** [comment]
Okay good, I will approve this PR once you have received all the other necessary approvals for open-sourcing. Feel free to tag me again.

**Review by marko-k0 — APPROVED** [review]

**Pull request merged**
